result = 1 + 2
result = 3
original_result = 3
result = 3 - 1
result = 2
original_result = 2
result = 2 * 2
result = 4
original_result = 4
result = 4 ** 3
result = 64
result = 64 + 8
result = 72
result = 72 % 7
result = 2
result = 72 // 2
result = 36
result = 1 + 2
print('result = ', result)
original_result = result
result = result - 1
print('result = ', result)
original_result = result
result = result * 2
print('result = ', result)
original_result = result
result = result ** 3
print('result = ', result)
result = result + 8
print('result =',  result)
result = result % 7
print('result = ', result)
result = result // 2
print('result', result)