result = 5
result = 1
result = 4
result = -4
notresult = False
result = 5
print('result =', result)
result = 1
print('result = ', result)
result += 3
print('result =', result)
result = - result
print('result =', result)
result = True
print('not result =', not result)